### ISSUE TITLE
Update startup scripts to systemd

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/system-playbooks#1]
From here on out, Ubuntu (and all the other distros) have switched to systemd.  We need to update the startup script instructions and configuration for systemd.

I'm still not sure o fthe best way to write a systemd startup script.  Right now, the apache one I'm using just callls apachectl. I'm hoping apache will provide a systemd script in the future.

**Comment by charlesbrandt** [comment]
Switching to using apt for services like apache and mysql seems to have fixed this.
