### ISSUE TITLE
ansible.cfg should exist and set variables specific to this repository

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/system-playbooks#2]
The ansible.cfg for this repository should contain non-secure settings needed to run the playbooks.  For instance, in order to run these playbooks, roles_path has to point to the roles directory inside this repository.  This should be set in an ansible.cfg in this repository.

**Comment by charlesbrandt** [comment]
Yeah, I mention this in the README.md under the "Ansible configuration defaults" section. If this repo is checked out to /etc/ansible I didn't want that config file to clobber anything... in that case the default ansible.cfg would probably work. 

I could also see including the default one with a note to update the roles location as part of the instructions, as you mentioned.

**Comment by inghamn** [comment]
Added in 6afd998d4afeb1a83a23a31ee92a449b7bf0e691
